version: "2.2"
services:

  mysql:
    build:
      context: ${MYSQL_BUILD_PATH}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_CONFIG_PATH}:/etc/my.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    restart: always
    networks:
      server:
        ipv4_address: ${MYSQL_IP}
    container_name: mysql

  nginx:
    build:
      context: ${NGINX_BUILD_PATH}
    depends_on:
      - php
      - redis
      - mongodb
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DIR_MAPPING}:/www
      - ${CONFIG_D_PATH}:/etc/nginx/conf.d
      - ${UPSTREAM_PATH}:/etc/nginx/upstream
      - ${CERT_PATH}:/etc/nginx/cert
      - ${NGINX_CONFIG}:/etc/nginx/nginx.conf
      - ${LOG_WWW_PATH}:/etc/nginx/log/www
      - ${ERROR_LOG_PATH}:/var/log/nginx/error.log
    networks:
      server:
        ipv4_address: ${NGINX_IP}
    restart: always
    container_name: nginx

  php:
    image: registry.cn-hangzhou.aliyuncs.com/ckall/php-swoole-git
#    build:
#      context: ${PHP_BUILD_PATH}
#      dockerfile: Dockerfile
#      args:
#        PHP_VERSION: ${PHP_VERSION}
    #原生构建太慢了如果你自己需要改的话就到上一个目录吧
    ports:
      - "9000"
      - "9502"
    volumes:
      - ${PHP_PROJECT_PATH}:/www
      - ${PHP_FPM_CONFIG_PATH}:/usr/local/etc/php-fpm.conf
      - ${PHP_VENDOR_PATH}:/usr/local/etc/php/conf.d
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini
      - ${PHP_HOSTS_PATH}:/etc/hosts
    networks:
      server:
        ipv4_address: ${PHP_IP}
    restart: always
    container_name: php
    stdin_open: true
    tty: true

  redis:
    build: ${REDIS_BUILD_PATH}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_CONFG_PATH}:/usr/local/etc/redis.conf
      - redis_data:/usr/local/redis/data
    #      - ${REDIS_LOGS_PATH}:/usr/local/redis/redis.log
    networks:
      server:
        ipv4_address: ${REDIS_HOST}
    restart: always
    container_name: redis

  mongodb:
    build: ${MONGO_BUILD_PATH}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    networks:
      server:
        ipv4_address: ${MONGO_HOST}
    restart: always
    container_name: mongodb
    command:
      --auth

  centrifugo:
    image: centrifugo/centrifugo:latest
    container_name: centrifugo
    volumes:
      - ${CENTRIFUGO_CONFIG_PATH}:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      server:
        ipv4_address:  172.27.0.9



#数据卷
volumes:
  mysql_data:
  mongo_data:
  redis_data:


networks:
  server:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24