version: "3"
services:
  owncloud:
    build:
      context: servers/owncloud
      dockerfile: servers/owncloud/Dockerfile
    ports:
      - 8001:80
    volumes:
      - owncloud_data:/var/www/html
    restart: always
    container_name: owncloud

volumes:
  owncloud_data: