version: "2.2"
services:

  mysql:
    build: ${MYSQL_BUILD_PATH}
    ports:
      - 3369:3306
    volumes:
      - ${MYSQL_CONFIG_PATH}:/etc/my.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: charles
    restart: always
    networks:
      server:
        ipv4_address: ${MYSQL_IP}
    container_name: mysql

  nginx:
    build: ${NGINX_BUILD_PATH}
    depends_on:
      - php
      - wordpress
      - redis
      - mongodb
      - mysql
      - team_standard
      - adminmysql
      - adminmongo
      - adminredis
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./perjects/php:/www
      - ${CONFIG_D_PATH}:/etc/nginx/conf.d
      - ${UPSTREAM_PATH}:/etc/nginx/upstream
      - ${CERT_PATH}:/etc/nginx/cert
      - ${NGINX_CONFIG}:/etc/nginx/nginx.conf
      - ${LOG_WWW_PATH}:/etc/nginx/log/www
      - ${ERROR_LOG_PATH}:/var/log/nginx/error.log
    networks:
      server:
        ipv4_address: ${NGINX_IP}
    restart: always
    container_name: nginx


  php:
    build: ./server/php
    #原生构建太慢了如果你自己需要改的话就到上一个目录吧
    #image: registry.cn-hangzhou.aliyuncs.com/ckall/php-swoole-git
    ports:
      - "9000"
      - "9502"
    volumes:
      - ./perjects/php:/www
      - ./server/php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./server/php/config/conf.d:/usr/local/etc/php/conf.d
      - ./server/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./server/php/etc/hosts:/etc/hosts
    networks:
      server:
        ipv4_address: 172.27.0.4
    restart: always
    container_name: php
    stdin_open: true
    tty: true

  redis:
    build: ./server/redis
    ports:
      - 6377:6379
    volumes:
      - ./server/redis/redis.conf:/usr/local/etc/redis.conf
      - ./server/redis/data:/usr/local/redis/data
      - ./server/redis/log/redis.log:/usr/local/redis/redis.log
    networks:
      server:
        ipv4_address: 172.27.0.5
    restart: always
    container_name: redis

  mongodb:
    build: ./server/mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db #db dir
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongodb"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    networks:
      server:
        ipv4_address: 172.27.0.6
    restart: always
    container_name: mongodb
    command:
      --auth


  adminredis:
    image: erikdubbelboer/phpredisadmin:latest
    depends_on:
      - redis
    networks:
      server:
        ipv4_address: 172.27.0.7
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - TZ=$TZ
    container_name: phpredisadmin

  adminmongo:
    image: mrvautin/adminmongo
    depends_on:
      - mongodb
    environment:
      - HOST=0.0.0.0
      - DB_HOST=mongodb
      - DB_PORT=27017
    networks:
      server:
        ipv4_address: 172.27.0.8
    container_name: adminmongo

  adminmysql:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    networks:
      server:
        ipv4_address: 172.27.0.9
    container_name: phpmyadmin
#数据卷
volumes:
  mysql_data:
  mongo_data:
  redis_data:


networks:
  server:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24