version: "2"
services:

  mysql:
    build: ./server/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./server/mysql/my.cnf:/etc/my.cnf
      - ./server/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
       server:
          ipv4_address: 172.66.0.2
    container_name: mysql

  nginx:
    build: ./server/nginx
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/www
      - ./server/nginx/conf.d:/etc/nginx/conf.d
      - ./server/nginx/cert:/etc/nginx/cert
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/nginx/log/error.log:/var/log/nginx/error.log
    networks:
      server:
        ipv4_address: 172.66.0.3
    restart: always
    container_name: nginx

  php:
    build: ./server/php
    volumes:
      -  ./www:/www
      - ./server/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./server/php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./server/php/config/php-fpm.d:/usr/local/etc/php-fpm.d
#      - ./server/etc/hosts:/etc/hosts
    networks:
      server:
        ipv4_address: 172.66.0.4
    restart: always
    container_name: php

  redis:
    build: ./server/redis
    ports:
      - "6379:6379"
    volumes:
      - ./server/redis/redis.conf:/usr/local/etc/redis.conf
      - ./server/redis/data:/usr/local/redis/data
      - ./server/redis/log/redis.log:/usr/local/redis/redis.log
    networks:
      server:
        ipv4_address: 172.66.0.5
    restart: always
    container_name: redis

  mongodb:
    build: ./server/mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./server/mongodb/mongo.conf:/etc/mongo/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongodb"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    networks:
      server:
        ipv4_address: 172.66.0.6
    restart: always
    container_name: mongodb
    command:
      --auth

  rabbitmq:
    build: ./server/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "123456"
    networks:
      server:
        ipv4_address: 172.66.0.7
    restart: always
    container_name: rabbitmq
#
#  yapi:
#    build: ./server/yapi
#    ports:
#      - "9090:9090"
#    networks:
#      server:
#        ipv4_address: 172.66.0.8
#    restart: always
#    container_name: yapi

networks:
  server:
    ipam:
      config:
        - subnet: 172.66.0.0/16
          gateway: 172.66.0.1