version: "2"
services:

  mysql:
    build: ./server/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./server/mysql/my.cnf:/etc/my.cnf
      - ./server/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
       server:
          ipv4_address: 172.66.0.6
    container_name: mysql

  nginx:
    build:
      context: ./server/nginx
    ports:
      - "80:80"
    volumes:
      - ./server/nginx/config:/etc/nginx
      - ./server/nginx/log:/var/log/nginx
    networks:
      server:
        ipv4_address: 172.66.0.2
    container_name: nginx

  redis:
    build: ./server/redis
    ports:
      - "6379:6379"
    volumes:
      - ./server/redis/redis.conf:/usr/local/etc/redis.conf
      - ./server/redis/data:/usr/local/redis/data
      - ./server/redis/log/redis.log:/usr/local/redis/redis.log
    networks:
      server:
        ipv4_address: 172.66.0.3
    restart: always
    container_name: redis

  mongodb:
    build: ./server/mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./server/mongodb/mongo.conf:/etc/mongo/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongodb"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    networks:
      server:
        ipv4_address: 172.66.0.4
    restart: always
    container_name: mongodb
    command:
      --auth

  rabbitmq:
    build: ./server/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "123456"
    networks:
      server:
        ipv4_address: 172.66.0.5
    restart: always
    container_name: rabbitmq
#
#  yapi:
#    build: ./server/yapi
#    ports:
#      - "9090:9090"
#    networks:
#      - client
#    restart: always
#    container_name: yapi

networks:
  server:
    ipam:
      config:
        - subnet: 172.66.0.0/16
          gateway: 172.66.0.1