################################################################################################################
#
# 注意开启kafka必须开启zook
#
################################################################################################################
version: '2.1'

services:
  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 172.19.0.11:2181,172.19.0.12:2181,172.19.0.13:2181
    volumes:
      - ./kafka1/logs:/kafka
    networks:
      kafka:
        ipv4_address: 172.27.4.14

  kafka2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: 172.19.0.11:2181,172.19.0.12:2181,172.19.0.13:2181
    volumes:
      - ./kafka2/logs:/kafka
    networks:
      kafka:
        ipv4_address: 172.27.4.15

  kafka3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - 9094:9094
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: 172.19.0.11:2181,172.19.0.12:2181,172.19.0.13:2181
    volumes:
      - ./kafka3/logs:/kafka
    networks:
      kafka:
        ipv4_address: 172.27.4.16

  kafka-manager:
    image: sheepkiller/kafka-manager            # 如果要安装web管理工具可以同时安装这个，最后通过苏主机IP的9000端口进行访问，例如172.31.148.174:9000
    environment:
      ZK_HOSTS: kafka1:62181,kafka2:62182,kafka3:62183
      APPLICATION_SECRET: "letmein"
    ports:
      - "39000:9000"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    expose:
      - "9000"
    networks:
      kafka:
        ipv4_address: 172.27.4.13
networks:
  kafka:
    ipam:
      config:
        - subnet: 172.27.4.0/24
          gateway: 172.27.4.1