version: "3"

services:
  apisix:
    image: apache/apisix
    restart: always
    volumes:
      - ${APISIX_LOGS}:/usr/local/apisix/logs
      - ${APISIXD_CONFIG}:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
    networks:
      - apisix


  dashboard:
    image: apache/apisix-dashboard
    restart: always
    volumes:
      - ${APISIXD_DASHBOARD_CONFIG}:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9000:9000/tcp"
    networks:
      - apisix

  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - etcd:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix

volumes:
  etcd:

networks:
  apisix:
    ipam:
      config:
        - subnet: 172.27.2.0/24
          gateway: 172.27.2.1

