version: "3.0"
services:
  wordpress:
    build:
      context: ./servers/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - ${WORDPRESS_CONFIG_PATH}:/usr/local/etc/php/conf.d/uploads.ini
      - wordpress_data:/var/www/html
    networks:
      projects:
        ipv4_address: 172.27.5.2
    restart: always

  team_standard:
    image: alicfeng/gitbook:team_standard
    networks:
      projects:
        ipv4_address: 172.27.5.3
    restart: always
    container_name: team_standard

  adminmysql:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=172.27.0.2
    networks:
      projects:
        ipv4_address: 172.27.5.4
    container_name: phpmyadmin

  jump:
    image: jumpserver/jms_all:v2.9.2
    ports:
      - 8030:80
      - 8020:2222
    entrypoint:
    networks:
      projects:
        ipv4_address: 172.27.5.5
    container_name: jump

  adminredis:
    image: erikdubbelboer/phpredisadmin:latest
    networks:
      projects:
        ipv4_address: 172.27.5.6
    environment:
      - REDIS_1_NAME=myredis
      - REDIS_1_HOST=172.27.0.5
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=charles
      - ADMIN_USER=cheng
      - ADMIN_PASS=charles
    container_name: phpredisadmin

  adminmongo:
    image: mrvautin/adminmongo
    environment:
      - HOST=172.27.0.6
      - DB_HOST=mongodb
      - DB_PORT=27017
    networks:
      projects:
        ipv4_address: 172.27.5.7
    container_name: adminmongo

  owncloud:
    build:
      context: servers/owncloud
      dockerfile: Dockerfile
    ports:
      - 8001:80
    volumes:
      - owncloud_data:/var/www/html
    restart: always
    container_name: owncloud

volumes:
  wordpress_data:
  owncloud_data:

networks:
  projects:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.5.0/24     