version: '2.4'
services:
  core:
    image: jumpserver/core:${JUMP_VERSION}
    container_name: jms_core
    restart: always
    tty: true
    command: start web
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${CONFIG_DIR}/core/config.yml:/opt/jumpserver/config.yml
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/core/logs:/opt/jumpserver/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      jumpnet:
        ipv4_address: 172.27.3.2

  luna:
    image: jumpserver/luna:${JUMP_VERSION}
    container_name: jms_luna
    restart: always
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -L http://localhost/luna/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      jumpnet:
        ipv4_address: 172.27.3.3

  lina:
    image: jumpserver/lina:${JUMP_VERSION}
    container_name: jms_lina
    restart: always
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -L http://localhost/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      jumpnet:
        ipv4_address: 172.27.3.4

  guacamole:
    image: jumpserver/guacamole:${JUMP_VERSION}
    container_name: jms_guacamole
    env_file:
      - ${CONFIG_FILE}
    restart: always
    volumes:
      - ${VOLUME_DIR}/guacamole/data:/config/guacamole/data
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      jumpnet:
        ipv4_address: 172.27.3.5
networks:
  jumpnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.3.0/24